version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lampungdev-web
    ports:
      - "3050:3050"
    command: sh -c "bun db:migrate && bun start"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/lampungdev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: lampungdev-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lampungdev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: