export type JobType = "Penuh Waktu" | "Paruh Waktu" | "Magang" | "Remote";

export type JobCategory =
  | "Web Development"
  | "Mobile Development"
  | "UI/UX Design"
  | "Data & AI"
  | "DevOps & Cloud"
  | "IT Support";

export interface Job {
  id: number;
  title: string;
  salary: string;
  type: JobType;
  experience: string;
  education: string;
  company: string;
  companyInitial: string;
  location: string;
  category: JobCategory;
  postedAt: string;
  isPremium: boolean;
  skills: string[];
  description: string;
  responsibilities: string[];
  requirements: string[];
  benefits: string[];
}

export const POPULAR_TAGS = [
  "Frontend Developer",
  "Backend Developer",
  "Fullstack",
  "UI/UX Designer",
  "Mobile Developer",
  "Data Analyst",
];

export const LOCATIONS = [
  "Semua Kota",
  "Bandar Lampung",
  "Metro",
  "Pringsewu",
  "Lampung Selatan",
  "Remote",
];

export const CATEGORY_TABS: string[] = [
  "Semua",
  "Web Development",
  "Mobile Development",
  "UI/UX Design",
  "Data & AI",
  "DevOps & Cloud",
  "IT Support",
];

export const JOB_CATEGORIES: { name: JobCategory; sub: string }[] = [
  { name: "Web Development", sub: "Frontend · Backend · Fullstack" },
  { name: "Mobile Development", sub: "Android · iOS · Flutter" },
  { name: "UI/UX Design", sub: "Product Design · Research" },
  { name: "Data & AI", sub: "Data Science · Machine Learning" },
  { name: "DevOps & Cloud", sub: "AWS · GCP · CI/CD" },
  { name: "IT Support", sub: "Helpdesk · Sistem Administrator" },
];

export const JOBS_DATA: Job[] = [
  {
    id: 1,
    title: "Frontend Developer (React)",
    salary: "Rp 5jt–8jt",
    type: "Penuh Waktu",
    experience: "1–3 tahun",
    education: "D3/S1",
    company: "PT Digital Nusantara",
    companyInitial: "DN",
    location: "Bandar Lampung",
    category: "Web Development",
    postedAt: "2 jam yang lalu",
    isPremium: false,
    skills: ["React", "TypeScript", "Tailwind CSS", "Git"],
    description:
      "Kami mencari seorang Frontend Developer yang berpengalaman dan bersemangat untuk bergabung dengan tim kami di PT Digital Nusantara. Anda akan bertanggung jawab membangun dan memelihara antarmuka pengguna yang responsif dan performatif untuk produk-produk digital kami yang melayani jutaan pengguna di Lampung dan sekitarnya.",
    responsibilities: [
      "Mengembangkan dan memelihara aplikasi web menggunakan React.js dan TypeScript",
      "Berkolaborasi dengan tim desain untuk mengimplementasikan UI/UX yang pixel-perfect",
      "Mengoptimalkan performa aplikasi untuk kecepatan dan skalabilitas maksimal",
      "Menulis unit test dan melakukan code review secara rutin",
      "Berkoordinasi dengan tim backend untuk integrasi API",
    ],
    requirements: [
      "Pengalaman minimal 1–3 tahun sebagai Frontend Developer",
      "Mahir dalam React.js, TypeScript, dan Tailwind CSS",
      "Pemahaman yang baik tentang HTML5, CSS3, dan JavaScript ES6+",
      "Pengalaman dengan Git dan workflow kolaborasi tim",
      "Kemampuan komunikasi yang baik dan mampu bekerja dalam tim",
    ],
    benefits: [
      "Gaji kompetitif Rp 5jt–8jt per bulan",
      "BPJS Kesehatan & Ketenagakerjaan",
      "Tunjangan makan dan transportasi",
      "Lingkungan kerja yang fleksibel dan suportif",
      "Peluang pengembangan karir dan training",
    ],
  },
  {
    id: 2,
    title: "Backend Developer (Node.js)",
    salary: "Rp 6jt–10jt",
    type: "Penuh Waktu",
    experience: "2–4 tahun",
    education: "S1",
    company: "Startup Lampung Tech",
    companyInitial: "SL",
    location: "Bandar Lampung",
    category: "Web Development",
    postedAt: "3 jam yang lalu",
    isPremium: true,
    skills: ["Node.js", "Express", "PostgreSQL", "Docker", "REST API"],
    description:
      "Startup Lampung Tech sedang berkembang pesat dan membutuhkan Backend Developer handal untuk membangun infrastruktur server yang kuat. Anda akan menjadi bagian dari tim engineering inti yang merancang dan mengembangkan API untuk platform e-commerce lokal kami.",
    responsibilities: [
      "Merancang dan mengembangkan RESTful API yang skalabel menggunakan Node.js",
      "Mengelola dan mengoptimalkan database PostgreSQL",
      "Mengimplementasikan mekanisme autentikasi dan keamanan aplikasi",
      "Melakukan deployment dan monitoring aplikasi menggunakan Docker",
      "Berkolaborasi dengan tim frontend untuk memastikan integrasi yang lancar",
    ],
    requirements: [
      "Pengalaman 2–4 tahun di bidang backend development",
      "Mahir dalam Node.js, Express.js, dan TypeScript",
      "Pengalaman dengan PostgreSQL atau database relasional lainnya",
      "Familiar dengan Docker dan konsep containerization",
      "Pemahaman solid tentang keamanan aplikasi web",
    ],
    benefits: [
      "Gaji Rp 6jt–10jt per bulan + bonus performa",
      "Saham/equity untuk karyawan awal",
      "Remote working 2 hari per minggu",
      "Budget untuk konferensi dan workshop teknologi",
      "Laptop kerja disediakan perusahaan",
    ],
  },
  {
    id: 3,
    title: "UI/UX Designer",
    salary: "Rp 4jt–7jt",
    type: "Penuh Waktu",
    experience: "1–2 tahun",
    education: "D3/S1",
    company: "CV Kreasi Digital Lampung",
    companyInitial: "KD",
    location: "Metro, Lampung",
    category: "UI/UX Design",
    postedAt: "5 jam yang lalu",
    isPremium: false,
    skills: ["Figma", "Adobe XD", "Prototyping", "User Research"],
    description:
      "CV Kreasi Digital Lampung membuka lowongan untuk UI/UX Designer yang kreatif dan berorientasi pada pengguna. Anda akan bekerja langsung dengan klien untuk memahami kebutuhan bisnis dan menerjemahkannya menjadi desain produk digital yang intuitif dan menarik.",
    responsibilities: [
      "Membuat wireframe, mockup, dan prototype interaktif menggunakan Figma",
      "Melakukan user research dan usability testing",
      "Mengembangkan dan memelihara design system yang konsisten",
      "Berkolaborasi dengan developer untuk memastikan implementasi sesuai desain",
      "Mempresentasikan konsep desain kepada klien dan stakeholder",
    ],
    requirements: [
      "Pengalaman 1–2 tahun sebagai UI/UX Designer",
      "Mahir menggunakan Figma dan tools desain lainnya",
      "Portofolio yang menunjukkan proyek desain mobile dan web",
      "Pemahaman tentang prinsip-prinsip UX dan user-centered design",
      "Kemampuan komunikasi yang baik untuk presentasi desain",
    ],
    benefits: [
      "Gaji Rp 4jt–7jt per bulan",
      "BPJS Kesehatan & Ketenagakerjaan",
      "Subsidi software dan tools desain",
      "Jadwal kerja fleksibel",
      "Portofolio proyek beragam dari berbagai industri",
    ],
  },
  {
    id: 4,
    title: "Flutter Mobile Developer",
    salary: "Rp 5jt–9jt",
    type: "Penuh Waktu",
    experience: "1–3 tahun",
    education: "S1",
    company: "PT Inovasi Sumatera",
    companyInitial: "IS",
    location: "Bandar Lampung",
    category: "Mobile Development",
    postedAt: "6 jam yang lalu",
    isPremium: true,
    skills: ["Flutter", "Dart", "Firebase", "REST API", "Git"],
    description:
      "PT Inovasi Sumatera mencari Flutter Developer berbakat untuk bergabung dalam pengembangan aplikasi mobile kami yang sedang tumbuh. Anda akan terlibat dalam seluruh siklus pengembangan, dari perencanaan fitur hingga deployment ke App Store dan Play Store.",
    responsibilities: [
      "Mengembangkan aplikasi cross-platform menggunakan Flutter dan Dart",
      "Mengintegrasikan API backend dan layanan Firebase",
      "Memastikan performa aplikasi yang optimal di berbagai perangkat",
      "Menulis kode yang bersih dan unit test yang komprehensif",
      "Berkoordinasi dengan tim UI/UX untuk pengalaman pengguna terbaik",
    ],
    requirements: [
      "Pengalaman 1–3 tahun dengan Flutter dan Dart",
      "Familiar dengan state management (Provider, Bloc, atau Riverpod)",
      "Pengalaman dengan Firebase (Auth, Firestore, FCM)",
      "Pernah mempublish aplikasi ke Google Play Store atau App Store",
      "Kemampuan problem-solving yang baik",
    ],
    benefits: [
      "Gaji Rp 5jt–9jt per bulan",
      "Bonus proyek dan performa tahunan",
      "BPJS Kesehatan & Ketenagakerjaan",
      "Perangkat mobile untuk testing disediakan",
      "Lingkungan kerja agile yang dinamis",
    ],
  },
  {
    id: 5,
    title: "Data Analyst",
    salary: "Rp 4jt–6jt",
    type: "Penuh Waktu",
    experience: "0–2 tahun",
    education: "S1",
    company: "Badan Digital Lampung",
    companyInitial: "BD",
    location: "Bandar Lampung",
    category: "Data & AI",
    postedAt: "1 hari yang lalu",
    isPremium: false,
    skills: ["Python", "SQL", "Tableau", "Excel", "Power BI"],
    description:
      "Badan Digital Lampung membuka kesempatan bagi lulusan baru dan junior analyst untuk bergabung dalam tim data kami. Anda akan membantu pengambilan keputusan berbasis data untuk program-program pemberdayaan digital di Provinsi Lampung.",
    responsibilities: [
      "Mengumpulkan, membersihkan, dan menganalisis data dari berbagai sumber",
      "Membuat laporan dan visualisasi data yang mudah dipahami stakeholder",
      "Mengidentifikasi tren dan wawasan bisnis dari data",
      "Berkoordinasi dengan berbagai departemen untuk kebutuhan data",
      "Memelihara database dan memastikan kualitas data",
    ],
    requirements: [
      "Lulusan S1 Statistik, Matematika, Informatika, atau bidang terkait",
      "Menguasai SQL dan setidaknya satu bahasa pemrograman (Python/R)",
      "Pengalaman dengan tools visualisasi (Tableau, Power BI, atau Excel)",
      "Kemampuan analitis dan perhatian terhadap detail yang tinggi",
      "Bersedia belajar dan berkembang dalam lingkungan kerja dinamis",
    ],
    benefits: [
      "Gaji Rp 4jt–6jt per bulan",
      "BPJS Kesehatan & Ketenagakerjaan",
      "Tunjangan perjalanan dinas",
      "Pelatihan dan sertifikasi data analytics",
      "Kesempatan berkontribusi pada program pemerintah daerah",
    ],
  },
  {
    id: 6,
    title: "Fullstack Developer (Next.js)",
    salary: "Rp 7jt–12jt",
    type: "Penuh Waktu",
    experience: "2–5 tahun",
    education: "S1",
    company: "PT Teknologi Maju Lampung",
    companyInitial: "TM",
    location: "Bandar Lampung",
    category: "Web Development",
    postedAt: "1 hari yang lalu",
    isPremium: true,
    skills: ["Next.js", "TypeScript", "PostgreSQL", "Prisma", "TailwindCSS"],
    description:
      "PT Teknologi Maju Lampung adalah perusahaan teknologi yang sedang membangun platform SaaS untuk UMKM di Sumatera. Kami mencari Fullstack Developer senior yang mampu merancang dan membangun produk dari nol dengan standar kualitas tinggi.",
    responsibilities: [
      "Merancang arsitektur aplikasi web yang skalabel menggunakan Next.js",
      "Membangun fitur end-to-end dari database hingga UI",
      "Mengoptimalkan performa aplikasi (Core Web Vitals, SEO)",
      "Mentoring junior developer dalam tim",
      "Berpartisipasi dalam perencanaan produk dan technical roadmap",
    ],
    requirements: [
      "Pengalaman 2–5 tahun dalam fullstack web development",
      "Mahir dalam Next.js, TypeScript, dan Tailwind CSS",
      "Pengalaman dengan ORM (Prisma/Drizzle) dan PostgreSQL",
      "Pemahaman tentang CI/CD, Git workflow, dan deployment",
      "Kemampuan kepemimpinan teknis dan mentoring",
    ],
    benefits: [
      "Gaji Rp 7jt–12jt per bulan + equity",
      "Remote working hingga 3 hari per minggu",
      "Budget pengembangan diri Rp 2jt per tahun",
      "Laptop MacBook disediakan",
      "Kesempatan memimpin tim teknis",
    ],
  },
  {
    id: 7,
    title: "Android Developer (Kotlin)",
    salary: "Rp 5jt–8jt",
    type: "Penuh Waktu",
    experience: "1–3 tahun",
    education: "S1",
    company: "CV Solusi Teknologi",
    companyInitial: "ST",
    location: "Pringsewu, Lampung",
    category: "Mobile Development",
    postedAt: "2 hari yang lalu",
    isPremium: false,
    skills: ["Kotlin", "Android SDK", "Jetpack Compose", "Room", "Retrofit"],
    description:
      "CV Solusi Teknologi membuka posisi Android Developer untuk memperkuat tim mobile kami di Pringsewu. Anda akan mengerjakan aplikasi Android native untuk sektor pertanian dan keuangan mikro yang melayani petani di Lampung Tengah dan sekitarnya.",
    responsibilities: [
      "Mengembangkan dan memelihara aplikasi Android menggunakan Kotlin",
      "Mengimplementasikan UI menggunakan Jetpack Compose",
      "Integrasi dengan API backend menggunakan Retrofit",
      "Mengelola lokal database menggunakan Room",
      "Melakukan testing dan debugging aplikasi di berbagai versi Android",
    ],
    requirements: [
      "Pengalaman 1–3 tahun dalam pengembangan Android native",
      "Mahir dalam Kotlin dan Android SDK",
      "Pengalaman dengan Jetpack libraries (Compose, Room, ViewModel, Navigation)",
      "Familiar dengan pola arsitektur MVVM atau Clean Architecture",
      "Bersedia berdomisili atau komuter ke Pringsewu",
    ],
    benefits: [
      "Gaji Rp 5jt–8jt per bulan",
      "BPJS Kesehatan & Ketenagakerjaan",
      "Tunjangan transportasi untuk komuter",
      "Proyek yang berdampak langsung pada petani lokal",
      "Lingkungan kerja kekeluargaan",
    ],
  },
  {
    id: 8,
    title: "DevOps Engineer",
    salary: "Rp 8jt–14jt",
    type: "Penuh Waktu",
    experience: "2–4 tahun",
    education: "S1",
    company: "PT Cloud Nusantara",
    companyInitial: "CN",
    location: "Bandar Lampung",
    category: "DevOps & Cloud",
    postedAt: "2 hari yang lalu",
    isPremium: false,
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD", "Linux"],
    description:
      "PT Cloud Nusantara membutuhkan DevOps Engineer yang berpengalaman untuk mengelola infrastruktur cloud kami yang terus berkembang. Anda akan bekerja pada sistem yang melayani ratusan klien korporat di Sumatera bagian selatan.",
    responsibilities: [
      "Merancang dan mengelola infrastruktur cloud menggunakan AWS",
      "Membangun dan memelihara pipeline CI/CD menggunakan GitHub Actions",
      "Mengimplementasikan orkestrasi container dengan Kubernetes",
      "Melakukan monitoring, alerting, dan incident response",
      "Menulis Infrastructure as Code menggunakan Terraform",
    ],
    requirements: [
      "Pengalaman 2–4 tahun sebagai DevOps atau Site Reliability Engineer",
      "Sertifikasi AWS (minimal AWS Cloud Practitioner atau Solutions Architect)",
      "Mahir dalam Docker, Kubernetes, dan Linux",
      "Pengalaman dengan tools monitoring (Grafana, Prometheus, atau CloudWatch)",
      "Pemahaman networking (VPC, Load Balancing, DNS)",
    ],
    benefits: [
      "Gaji Rp 8jt–14jt per bulan",
      "Subsidi sertifikasi cloud (AWS, GCP)",
      "Fully remote working",
      "Tunjangan internet dan listrik",
      "On-call allowance",
    ],
  },
  {
    id: 9,
    title: "Magang UI/UX Designer",
    salary: "Rp 500rb–1,5jt",
    type: "Magang",
    experience: "Fresh Graduate",
    education: "D3/S1",
    company: "Studio Kreatif Lampung",
    companyInitial: "SK",
    location: "Bandar Lampung",
    category: "UI/UX Design",
    postedAt: "3 hari yang lalu",
    isPremium: false,
    skills: ["Figma", "Canva", "Adobe Illustrator", "Prototyping"],
    description:
      "Studio Kreatif Lampung membuka program magang untuk desainer muda yang ingin mengembangkan kemampuan UI/UX. Ini adalah kesempatan emas untuk belajar langsung dari para profesional dan membangun portofolio yang kuat selama 3–6 bulan.",
    responsibilities: [
      "Membantu tim desain dalam membuat wireframe dan mockup",
      "Melakukan riset kompetitor dan tren desain terkini",
      "Membuat aset visual untuk keperluan digital marketing",
      "Mengikuti proses desain dari brief hingga final deliverable",
      "Belajar dan menerapkan feedback dari senior designer",
    ],
    requirements: [
      "Mahasiswa semester akhir atau fresh graduate desain/informatika",
      "Mengenal tools desain (minimal Figma atau Adobe XD)",
      "Memiliki portofolio desain (bisa berupa tugas kuliah)",
      "Antusias belajar dan tidak takut menerima feedback",
      "Berkomitmen selama 3–6 bulan program magang",
    ],
    benefits: [
      "Uang saku Rp 500rb–1,5jt per bulan",
      "Mentoring intensif dari senior designer",
      "Sertifikat magang resmi",
      "Kesempatan langsung jadi karyawan tetap",
      "Portofolio proyek nyata",
    ],
  },
  {
    id: 10,
    title: "iOS Developer (Swift)",
    salary: "Rp 6jt–10jt",
    type: "Penuh Waktu",
    experience: "2–4 tahun",
    education: "S1",
    company: "PT Inovasi Sumatera",
    companyInitial: "IS",
    location: "Bandar Lampung",
    category: "Mobile Development",
    postedAt: "3 hari yang lalu",
    isPremium: true,
    skills: ["Swift", "SwiftUI", "UIKit", "Xcode", "CoreData"],
    description:
      "PT Inovasi Sumatera membuka posisi iOS Developer untuk melengkapi tim mobile kami. Anda akan mengembangkan aplikasi iOS native yang digunakan oleh ribuan pengguna di Lampung dan berkolaborasi erat dengan tim Flutter untuk konsistensi fitur lintas platform.",
    responsibilities: [
      "Mengembangkan fitur baru untuk aplikasi iOS menggunakan Swift dan SwiftUI",
      "Memelihara dan meningkatkan kode legacy UIKit",
      "Berkoordinasi dengan tim backend untuk integrasi API",
      "Memastikan kualitas aplikasi melalui unit test dan UI test",
      "Mengikuti App Store review guidelines dan best practices Apple",
    ],
    requirements: [
      "Pengalaman 2–4 tahun dalam pengembangan iOS native",
      "Mahir dalam Swift dan SwiftUI",
      "Familiar dengan UIKit untuk maintenance kode lama",
      "Pengalaman publish aplikasi ke App Store",
      "Pemahaman tentang Human Interface Guidelines Apple",
    ],
    benefits: [
      "Gaji Rp 6jt–10jt per bulan",
      "MacBook Pro disediakan untuk pengembangan",
      "Apple Developer Account disubsidi",
      "BPJS Kesehatan & Ketenagakerjaan",
      "Hybrid working (3 hari kantor, 2 hari remote)",
    ],
  },
  {
    id: 11,
    title: "Machine Learning Engineer",
    salary: "Rp 9jt–15jt",
    type: "Penuh Waktu",
    experience: "2–5 tahun",
    education: "S1/S2",
    company: "AgriTech Lampung",
    companyInitial: "AL",
    location: "Bandar Lampung",
    category: "Data & AI",
    postedAt: "4 hari yang lalu",
    isPremium: true,
    skills: ["Python", "TensorFlow", "PyTorch", "scikit-learn", "MLflow"],
    description:
      "AgriTech Lampung adalah startup agrikultur berbasis AI yang membantu petani meningkatkan produktivitas melalui teknologi. Kami mencari ML Engineer untuk mengembangkan model prediksi panen, deteksi hama, dan rekomendasi pupuk berbasis data sensor dan citra satelit.",
    responsibilities: [
      "Merancang dan melatih model machine learning untuk prediksi pertanian",
      "Mengolah dataset citra satelit dan sensor IoT skala besar",
      "Membangun dan mendeploy model ML ke production menggunakan MLflow",
      "Berkolaborasi dengan tim data engineering dan backend",
      "Melakukan penelitian dan eksperimen untuk meningkatkan akurasi model",
    ],
    requirements: [
      "Pengalaman 2–5 tahun dalam machine learning atau data science",
      "Mahir dalam Python, TensorFlow atau PyTorch",
      "Pengalaman dengan computer vision atau time series analysis",
      "Familiar dengan cloud ML services (AWS SageMaker atau GCP AI Platform)",
      "Kemampuan komunikasi teknis yang baik",
    ],
    benefits: [
      "Gaji Rp 9jt–15jt per bulan + equity",
      "Budget penelitian dan publikasi ilmiah",
      "Remote-first working culture",
      "Akses ke dataset pertanian unik di Indonesia",
      "Konferensi AI/ML nasional dan internasional",
    ],
  },
  {
    id: 12,
    title: "React Native Developer",
    salary: "Rp 5jt–8,5jt",
    type: "Penuh Waktu",
    experience: "1–3 tahun",
    education: "D3/S1",
    company: "CV Aplikasi Nusantara",
    companyInitial: "AN",
    location: "Bandar Lampung",
    category: "Mobile Development",
    postedAt: "4 hari yang lalu",
    isPremium: false,
    skills: ["React Native", "JavaScript", "Redux", "Expo", "REST API"],
    description:
      "CV Aplikasi Nusantara membutuhkan React Native Developer untuk mengembangkan aplikasi mobile untuk klien-klien di sektor retail dan logistik. Anda akan bekerja pada beberapa proyek sekaligus dengan timeline yang variatif.",
    responsibilities: [
      "Mengembangkan aplikasi mobile cross-platform menggunakan React Native",
      "Mengelola state aplikasi menggunakan Redux atau Zustand",
      "Mengintegrasikan berbagai library third-party dan native module",
      "Melakukan debugging dan optimasi performa aplikasi",
      "Berkoordinasi langsung dengan klien untuk kebutuhan fitur",
    ],
    requirements: [
      "Pengalaman 1–3 tahun dengan React Native",
      "Mahir dalam JavaScript/TypeScript dan React",
      "Pengalaman dengan Expo workflow",
      "Pernah mempublish aplikasi ke kedua platform (iOS dan Android)",
      "Kemampuan bekerja di bawah tekanan dengan deadline ketat",
    ],
    benefits: [
      "Gaji Rp 5jt–8,5jt per bulan",
      "Bonus penyelesaian proyek",
      "BPJS Kesehatan & Ketenagakerjaan",
      "Jam kerja fleksibel",
      "Portofolio proyek dari berbagai industri",
    ],
  },
  {
    id: 13,
    title: "Data Engineer",
    salary: "Rp 7jt–11jt",
    type: "Penuh Waktu",
    experience: "2–4 tahun",
    education: "S1",
    company: "PT Mitra Data Indonesia",
    companyInitial: "MD",
    location: "Metro, Lampung",
    category: "Data & AI",
    postedAt: "5 hari yang lalu",
    isPremium: false,
    skills: ["Python", "Apache Spark", "Airflow", "dbt", "BigQuery"],
    description:
      "PT Mitra Data Indonesia adalah perusahaan konsultasi data yang melayani klien korporat dan pemerintah. Kami mencari Data Engineer untuk membangun dan mengelola pipeline data yang handal dan efisien guna mendukung kebutuhan analitik klien kami.",
    responsibilities: [
      "Membangun dan memelihara data pipeline menggunakan Apache Airflow",
      "Mengolah dan mentransformasi data skala besar menggunakan PySpark",
      "Membangun data warehouse dan data mart menggunakan dbt",
      "Memastikan kualitas, ketersediaan, dan keamanan data",
      "Berkoordinasi dengan tim data analyst dan business stakeholder",
    ],
    requirements: [
      "Pengalaman 2–4 tahun sebagai Data Engineer",
      "Mahir dalam SQL dan Python",
      "Pengalaman dengan tools orchestration (Airflow, Prefect)",
      "Familiar dengan cloud data warehouse (BigQuery, Redshift, atau Snowflake)",
      "Pemahaman tentang data modeling dan schema design",
    ],
    benefits: [
      "Gaji Rp 7jt–11jt per bulan",
      "Tunjangan sertifikasi cloud",
      "Hybrid working",
      "Proyek dari berbagai industri (keuangan, retail, pemerintahan)",
      "BPJS Kesehatan & Ketenagakerjaan",
    ],
  },
  {
    id: 14,
    title: "Cloud Architect (AWS)",
    salary: "Rp 15jt–25jt",
    type: "Penuh Waktu",
    experience: "5+ tahun",
    education: "S1",
    company: "PT Cloud Nusantara",
    companyInitial: "CN",
    location: "Remote",
    category: "DevOps & Cloud",
    postedAt: "5 hari yang lalu",
    isPremium: true,
    skills: ["AWS", "Terraform", "Kubernetes", "Security", "Cost Optimization"],
    description:
      "PT Cloud Nusantara membuka posisi Cloud Architect senior untuk memimpin transformasi cloud klien-klien enterprise kami. Anda akan menjadi trusted advisor bagi klien dan memimpin tim DevOps dalam perancangan solusi cloud yang aman dan cost-effective.",
    responsibilities: [
      "Merancang arsitektur cloud yang skalabel dan aman untuk klien enterprise",
      "Memimpin migrasi aplikasi on-premise ke AWS",
      "Melakukan review keamanan dan kepatuhan cloud infrastructure",
      "Mengoptimalkan biaya infrastruktur cloud klien",
      "Membimbing dan mentoring tim DevOps junior",
    ],
    requirements: [
      "Pengalaman 5+ tahun dalam cloud architecture",
      "Sertifikasi AWS Solutions Architect Professional",
      "Pemahaman mendalam tentang keamanan cloud dan compliance",
      "Pengalaman dengan multi-cloud dan hybrid cloud environment",
      "Kemampuan presentasi dan komunikasi dengan C-level executives",
    ],
    benefits: [
      "Gaji Rp 15jt–25jt per bulan + performance bonus",
      "Fully remote dengan allowance home office",
      "Subsidi sertifikasi AWS tanpa batas",
      "Saham/equity perusahaan",
      "Flexible working hours",
    ],
  },
  {
    id: 15,
    title: "IT Support Specialist",
    salary: "Rp 3jt–4,5jt",
    type: "Penuh Waktu",
    experience: "0–2 tahun",
    education: "D3/S1",
    company: "PT Perdagangan Lampung Jaya",
    companyInitial: "LJ",
    location: "Lampung Selatan",
    category: "IT Support",
    postedAt: "1 minggu yang lalu",
    isPremium: false,
    skills: ["Windows", "Networking", "Hardware", "Active Directory", "Helpdesk"],
    description:
      "PT Perdagangan Lampung Jaya membutuhkan IT Support Specialist untuk mengelola infrastruktur IT di kantor pusat kami di Lampung Selatan. Posisi ini cocok untuk fresh graduate yang ingin memulai karir di bidang IT dan mendapatkan pengalaman kerja nyata.",
    responsibilities: [
      "Memberikan dukungan teknis kepada pengguna untuk masalah hardware dan software",
      "Mengelola dan memelihara jaringan LAN/WAN kantor",
      "Melakukan instalasi, konfigurasi, dan troubleshooting komputer",
      "Mengelola user account dan akses menggunakan Active Directory",
      "Mendokumentasikan setiap insiden dan solusi yang diberikan",
    ],
    requirements: [
      "Lulusan D3/S1 Teknik Informatika atau Sistem Informasi",
      "Memahami dasar-dasar networking (TCP/IP, DHCP, DNS)",
      "Familiar dengan sistem operasi Windows Server dan client",
      "Kemampuan troubleshooting hardware komputer",
      "Komunikatif, sabar, dan berorientasi pada kepuasan pengguna",
    ],
    benefits: [
      "Gaji Rp 3jt–4,5jt per bulan",
      "BPJS Kesehatan & Ketenagakerjaan",
      "Tunjangan makan harian",
      "Training on-the-job",
      "Jenjang karir yang jelas",
    ],
  },
  {
    id: 16,
    title: "PHP/Laravel Developer",
    salary: "Rp 4jt–7jt",
    type: "Penuh Waktu",
    experience: "1–3 tahun",
    education: "D3/S1",
    company: "CV Web Solusi Lampung",
    companyInitial: "WS",
    location: "Bandar Lampung",
    category: "Web Development",
    postedAt: "1 minggu yang lalu",
    isPremium: false,
    skills: ["PHP", "Laravel", "MySQL", "Vue.js", "REST API"],
    description:
      "CV Web Solusi Lampung adalah perusahaan pengembang web yang melayani klien dari sektor pemerintahan, pendidikan, dan UMKM. Kami mencari Laravel Developer untuk membantu membangun sistem informasi berbasis web bagi klien-klien kami.",
    responsibilities: [
      "Mengembangkan aplikasi web menggunakan framework Laravel",
      "Merancang dan mengelola database MySQL",
      "Membangun API untuk integrasi dengan aplikasi frontend dan mobile",
      "Melakukan code review dan memastikan keamanan aplikasi",
      "Mendokumentasikan kode dan API yang dikembangkan",
    ],
    requirements: [
      "Pengalaman 1–3 tahun dengan PHP dan Laravel",
      "Memahami MVC architecture dan ORM Eloquent",
      "Familiar dengan MySQL dan desain database relasional",
      "Pengalaman dengan Vue.js atau framework frontend lainnya menjadi nilai plus",
      "Pengalaman integrasi payment gateway (Midtrans, dll) lebih diutamakan",
    ],
    benefits: [
      "Gaji Rp 4jt–7jt per bulan",
      "BPJS Kesehatan & Ketenagakerjaan",
      "Bonus proyek",
      "Jam kerja fleksibel",
      "Lingkungan kerja santai namun produktif",
    ],
  },
  {
    id: 17,
    title: "QA Engineer",
    salary: "Rp 4,5jt–7jt",
    type: "Penuh Waktu",
    experience: "1–3 tahun",
    education: "D3/S1",
    company: "Startup Lampung Tech",
    companyInitial: "SL",
    location: "Bandar Lampung",
    category: "Web Development",
    postedAt: "1 minggu yang lalu",
    isPremium: false,
    skills: ["Selenium", "Cypress", "Postman", "JIRA", "Manual Testing"],
    description:
      "Startup Lampung Tech membuka posisi QA Engineer untuk memastikan kualitas produk kami sebelum sampai ke tangan pengguna. Anda akan bekerja erat dengan tim developer dan product manager dalam siklus pengembangan Agile.",
    responsibilities: [
      "Membuat test plan, test case, dan test script berdasarkan requirements",
      "Melakukan manual testing dan automated testing menggunakan Cypress",
      "Melakukan API testing menggunakan Postman",
      "Melaporkan dan melacak bug menggunakan JIRA",
      "Berpartisipasi dalam sprint planning dan daily standup",
    ],
    requirements: [
      "Pengalaman 1–3 tahun sebagai QA Engineer",
      "Pengalaman dengan automated testing framework (Selenium, Cypress)",
      "Mahir dalam API testing menggunakan Postman",
      "Familiar dengan metodologi Agile/Scrum",
      "Teliti, detail-oriented, dan memiliki quality mindset yang kuat",
    ],
    benefits: [
      "Gaji Rp 4,5jt–7jt per bulan",
      "BPJS Kesehatan & Ketenagakerjaan",
      "Remote working 2 hari per minggu",
      "Akses ke tools testing premium",
      "Lingkungan startup yang inovatif",
    ],
  },
  {
    id: 18,
    title: "Network Administrator",
    salary: "Rp 4jt–6,5jt",
    type: "Penuh Waktu",
    experience: "1–3 tahun",
    education: "D3/S1",
    company: "PT Koneksi Lampung",
    companyInitial: "KL",
    location: "Bandar Lampung",
    category: "IT Support",
    postedAt: "2 minggu yang lalu",
    isPremium: false,
    skills: ["Cisco", "MikroTik", "Linux", "VPN", "Firewall"],
    description:
      "PT Koneksi Lampung adalah penyedia layanan internet (ISP) lokal yang melayani pelanggan residensial dan korporat di Lampung. Kami mencari Network Administrator untuk mengelola dan mengoptimalkan infrastruktur jaringan kami agar tetap stabil dan handal.",
    responsibilities: [
      "Mengelola dan mengkonfigurasi perangkat jaringan (Cisco, MikroTik)",
      "Monitoring jaringan 24/7 dan merespons insiden secara cepat",
      "Mengimplementasikan kebijakan keamanan jaringan dan firewall",
      "Mengelola VPN dan konektivitas antar kantor",
      "Mendokumentasikan topologi dan konfigurasi jaringan",
    ],
    requirements: [
      "Pengalaman 1–3 tahun sebagai Network Administrator",
      "Mahir dalam konfigurasi Cisco dan MikroTik",
      "Pemahaman mendalam tentang protokol jaringan (BGP, OSPF, VLAN)",
      "Pengalaman dengan Linux server administration",
      "Sertifikasi CCNA atau MikroTik MTCNA lebih diutamakan",
    ],
    benefits: [
      "Gaji Rp 4jt–6,5jt per bulan",
      "BPJS Kesehatan & Ketenagakerjaan",
      "Subsidi sertifikasi Cisco/MikroTik",
      "Tunjangan on-call",
      "Internet gratis di rumah",
    ],
  },
];
